# Generated by Django 5.2.4 on 2025-10-10 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontuacao',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='pontuacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='codigo_resgate',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='data_resgate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='promocao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocao'),
        ),
        migrations.RemoveField(
            model_name='pontuacao',
            name='data_ultima_atualizacao',
        ),
    ]
