# Generated by Django 5.2.4 on 2025-12-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pontuacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'unique_together': {('nome', 'estado')},
            },
        ),
        migrations.AlterField(
            model_name='comercio',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comercios', to='core.cidade'),
        ),
    ]
