# Generated by Django 5.2.4 on 2025-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cidade_alter_comercio_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='estado',
        ),
        migrations.AddField(
            model_name='comercio',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
