# Generated by Django 5.2.4 on 2026-02-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_comercio_estado_comercio_cnpj_comercio_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='sem_prazo',
            field=models.BooleanField(default=False, verbose_name='Sem data de validade'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
