# Generated by Django 5.2.4 on 2025-07-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome Completo'),
        ),
    ]
