# Generated by Django 5.2.4 on 2025-10-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('comerciante', 'Comerciante')], max_length=20),
        ),
    ]
